[workspace]
resolver = "2"
members = ["frosty_alloc"]

[package]
name = "frosty_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
hashbrown = "*"


[dependencies]
frosty_alloc = { path = "frosty_alloc" }
