[workspace]
resolver = "2"
members = [ "engine_core","frosty_alloc","render"]

[package]
name = "frosty_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
log = "*"
env_logger = "*"
winit = "0.29.*"
wgpu = "0.19.*"
bytemuck = { version = "1.12", features = ["derive"] }

hashbrown = "*"

[dependencies]
frosty_alloc = { path = "frosty_alloc" }
